### ISSUE TITLE
Error message running curl

### ISSUE THREAD

**Issue by ericsegovia** [aws-samples/nft-deployment-amazon-managed-blockchain#1]
Hi, when I try to do the curl for the deploy I get the following message: 

`{"Message":"User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:***:********/nftapi/POST/ with an explicit deny"`

How can I fix this message?

Thanks

**Comment by ericsegovia** [comment]
As a temporal solution I am testing the POST method in API Gateway and paste the deploy json and get the following answer:
<img width="2096" alt="Captura de Pantalla 2022-01-17 a la(s) 19 33 36" src="https://user-images.githubusercontent.com/16419564/149855632-48c30811-5ed3-46f0-b09f-e6c7f6749f11.png">

**Comment by pravinva** [comment]
>  {"Message":"User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:***:********/nftapi/POST/ with an explicit deny"

This error is thrown because the resource policy attached to the API gateway may not have whitelisted any valid IP addresses. When you deployed the stack, did you provide an IP address as an input? if you have, are running the curl command from the same IP?

**Comment by ericsegovia** [comment]
Thank you for the response @pravinva , I can now make the Curl correctly.

Now I get the following response:

`{"message":null,"code":"ParameterNotFound","time":"2022-01-18T14:42:20.247Z","requestId":"4122e193-c059-420e-b683-3fdfcb503df3","statusCode":400,"retryable":false,"retryDelay":30.2882440371123}`

I can tell that it is entering the switch statement in the index.js file but the error message is not clear, any clues on what could be happening?

Thank you

**Comment by pravinva** [comment]
Can you check if the pvt key has been generated and stored in the
ethSystemKey parameter in ssm? The sam template does not do this and needs
to be done separately.

Pravin

**Comment by ericsegovia** [comment]
Thank you for your help, now it is working.
