### ISSUE TITLE
The NFT metadata (image, name, description) didn't shown with the NFT

### ISSUE THREAD

**Issue by ronsoronso** [aws-samples/nft-deployment-amazon-managed-blockchain#2]
Thank you for sharing the steps and I'm able to deploy and mint the NFT. I can import the NFT to the wallet (rinkeby testnet).

However, the metadata (description, name) and the image didn't show up with the NFT, anyone can shed some light on that please? (checked the metadata.json is in the S3 bucket)

**Comment by pravinva** [comment]
Hi @ronsoronso ,
Are you using Metamask? It may likely require you to add the NFT IDs manually in the wallet  as described here https://metamask.zendesk.com/hc/en-us/articles/360058238591-NFT-tokens-in-your-MetaMask-wallet

Have you checked in Etherscan (or any rinkeby block explorer) if the NFT has been transferred to the wallet address?

**Comment by ronsoronso** [comment]
Hi @pravinva thank you for your reply, I've added the NFT to the MetaMask wallet, however, the NFT didn't shown the metadata and the NFT do not have the image:
![nftimage](https://user-images.githubusercontent.com/74066879/151690104-fc9c1342-b4fd-4d8c-8016-51bfd2eb87c0.png)

**Comment by ronsoronso** [comment]
Hi @pravinva 
I tried to get the token metadata using some of the APIs on the Internet and found that the metadata of the token is as follows, not sure if I did something incorrect in the deploy step?
![image](https://user-images.githubusercontent.com/74066879/151698329-fca191c3-d7d7-4c80-8854-01fb7f3e9284.png)


I didn't add the 0 in the metadata.json file name, and the following are the parameters I've used in the deploy.json:

{
"requestType": "deploy",
"tokenName": "coolnft",
"tokenTicker": "SYMB",
"metadataFilename": "metadata.json",
 "metadata":{
  "description": "Description of the NFT",     
  "image": "(url of the image)",
  "name": "Cool NFT"
  }
}

**Comment by pravinva** [comment]
@ronsoronso, 0 is likely the token ID. In the nft contract constructor, we set the baseURI with only the url of the metadata.json. I'll try to get more information.

**Comment by ronsoronso** [comment]
Hi @pravinva 
I guess the contract constructor took the whole URL of the metadata.json as the baseURI i.e. https://xxx.s3.amazonaws.com/metadata.json and then the constructor append the tokenID as the suffix. Or the constructor is trying to create a metadata file using the token ID as the file name as it believe the URI provided is only "https://xxx.s3.amazonaws.com/" e.g. https://xxx.s3.amazonaws.com/0.json ?

Is that something need to be revised on the NFT_BaseURI.sol ?
May you share guidance please?

**Comment by pravinva** [comment]
Hi,

We are working on a fix. You are correct about the URI -The token URI
should be https://xxx.s3.amazonaws.com/0.

**Comment by pravinva** [comment]
@ronsoronso To unblock your issue,  make the following changes
a.  cd serverless/lambdas/nftmain/index.js 
Change line 30 const s3URI  = `https://${bucketName}.s3.${region}.amazonaws.com/${metadataFilename}`;
to const s3URI  = `https://${bucketName}.s3.${region}.amazonaws.com/`; 
( i.e remove metadataFilename)

b. While deploying, in serverless/test-events/deploy.json change the value of "metadataFilename" from metadata.json to "0"

in serverless directory: sam build; sam deploy; y once more.

Then run the deploy command and mint command once again.
Note: this will only work for 1 token per contract. 
Please let me know if this solves your problem

thanks

**Comment by pravinva** [comment]
@ronsoronso Were you able to try the changes suggested? How did it go?

**Comment by pravinva** [comment]
closing issue
