### ISSUE TITLE
Clarifing which permissions are required to allow the execution of this sample

### ISSUE THREAD

**Issue by advapiIT** [aws-samples/nft-deployment-amazon-managed-blockchain#4]
Hello,
Can you please put inside your guide what are the required permission an user need to be able to execute such a sample?

Currently I've been given the following access

```
IAMFullAccess
AmazonS3FullAccess
AmazonAPIGatewayAdministrator
AmazonECS_FullAccess
AmazonVPCFullAccess
AmazonSNSFullAccess
AmazonManagedBlockchainFullAccess
AWSCloudFormationFullAccess
AmazonEKSFargatePodExecutionRolePolicy
AWSLambda_FullAccess
AmazonAPIGatewayPushToCloudWatchLogs
CloudWatchLogsFullAccess
AmazonManagedBlockchainConsoleFullAccess
```

Am I missing something?
Thanks

**Comment by pravinva** [comment]
Hi
You'll need SSM access as well

**Comment by advapiIT** [comment]
Excuse me SSM stays for? I've asked for the permission but the admin hasn't found it...thanks

**Comment by pravinva** [comment]
You need AWS Systems Manager (SSM)  to store the ethSystemKey as documented

**Comment by advapiIT** [comment]
oK thanks, I've been able to execute the script... I can't understand why I
can only create bc.t3.large > node but if I use bc.t3.small/medium I got a
400 error... in eu-west-1 eu-west-2, but I'm trying to find some info online
Thanks

**Comment by pravinva** [comment]
@advapiIT -  for region infrastructure related questions, please raise a ticket to AWS if required. The code works on all instance types supported by Amazon blockchain

**Comment by advapiIT** [comment]
Thanks for the info @pravinva , I close this since the question regarding permission is resolved. Thank again
