### ISSUE TITLE
"Cannot estimate gas; transaction may fail or may require manual gas limit" when deploying the contract

### ISSUE THREAD

**Issue by advapiIT** [aws-samples/nft-deployment-amazon-managed-blockchain#5]
Hello,
I've followed your guide and have reached the point where I have to push the contract on the rinkeby network... when I do the

```
curl -X POST https://<api>.execute-api.<region>.amazonaws.com/nftapi -H "Content-Type: application/json" -d @deploy.json
```
I've edited the url of the deploy.json and placed this as url https://gateway.pinata.cloud/ipfs/QmVq2nqVa3NvGTvgBS5iwG8XtwLZ5aKE4ttvn5q1XfjHj5?preview=1

I got the following error

```
{"Error":{"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"code":-32000},"method":"estimateGas","transaction":{"from":"0xEC40D5587045346f0D107D746786ADfaa3d7E4D3","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x9502f900"},"maxFeePerGas":{"type":"BigNumber","hex":"0xba12f2cc"},"data":"<data>","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0xba12f2cc"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x9502f900"},"nonce":{},"gasLimit":{},"chainId":{}}}}
```

I've got 1 ETH in my test wallet ... where can I check what's going on?
Thanks

**Comment by pravinva** [comment]
Can you check (perhaps on etherscan.io) if you've added the test eth to the correct wallet. it should be in the sending wallet and not the receiving one which is used for receiving the minted token. (i,e the wallet associated with the pvt key stored in ssm)
ethers library does not seem to provide better handling for such errors, but from experience, this error is likely because you may have not added token to the correct wallet

**Comment by advapiIT** [comment]
Hello,
Yes as you can see i've got the eth [here](https://rinkeby.etherscan.io/address/0x1Eccba5f2133bEBD720B291ab269b51ba426Ee66)
 for what concern the private key I had to use the following script to retrive it

```
var keythereum = require("keythereum");
var datadir = "C:\\Users\\xxx\\AppData\\Local\\Ethereum\\rinkeby";
var address= "0x1Eccba5f2133bEBD720B291ab269b51ba426Ee66";
const password = "MyPWD!!!";

and I got a string as bab6b0f5cf16287ed6042386f44329a647bb4c9e3772776244484d996fc36c38 is this one I have to put in the SSM?

I got a different error now... no more error on gas fee but got

```
{"Error":{"code":-32000,"transaction":{"type":2,"chainId":4,"nonce":0,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x9502f900"},"maxFeePerGas":{"type":"BigNumber","hex":"0xc58369ea"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0xc350"},"to":null,"value":{"type":"BigNumber","hex":"0x00"},"data":"<data>","accessList":[],"hash":"0x864a7a6c60192362d842d9d2a407351c2f94814bf82a652ec10823b6d6640ad8","v":0,"r":"0x60a01e3e991f69f1de6a3ec1c8f330b28bad2af0fce157cd121eb4e0025e7220","s":"0x3fb2a4e6d8bfd3ad00b95a323beddac396972935f988e0edc96a6d57fed747e1","from":"0x1Eccba5f2133bEBD720B291ab269b51ba426Ee66","confirmations":0},"transactionHash":"0x864a7a6c60192362d842d9d2a407351c2f94814bf82a652ec10823b6d6640ad8"}}
````

What is -32000?

Thanks

**Comment by pravinva** [comment]
Debugging ethers library errors is beyond the scope of this activity. I have uploaded a zip file with an utility to create pvt keys and corresponding wallet address under misc/create-eth-wallet.zip.  Please unzip it, and run the shell utility provided to  generate the credentials and then follow instructions

**Comment by advapiIT** [comment]
Pravin thanks for your reply, now I'll try your utility, but what I'm
trying to understand is if it's an error on my side (I've followed
literally the tutorial) or if there's something I'm missing

Thanks

**Comment by pravinva** [comment]
@advapiIT Please let me know if you were able to get your setup working and can close this issue?

**Comment by advapiIT** [comment]
Hello @pravinva , using your app to create  private key worked flawlessy
Thanks!

**Comment by pravinva** [comment]
closing issue
